list = ["Dan","Caton","07501839582","First item","Just Blaze","4:20"]

print(" __________________________________ ")
print("|  First Name  |  {0:<15}  |".format(list[0]))
print("|--------------|-------------------|")
print("|   Last Name  |  {0:<15}  |".format(list[1]))
print("|--------------|-------------------|")
print("|Phone number  |  {0:<15}  |".format(list[2]))
print("|--------------|-------------------|")
print("|      Adress  |  {0:<15}  |".format(list[3]))
print("|--------------|-------------------|")
print("|       Thing  |  {0:<15}  |".format(list[4]))
print("|--------------|-------------------|")
print("|        Blah  |  {0:<15}  |".format(list[5]))
print("|--------------|-------------------|")
